platform :ios, '8.0'

use_frameworks!

target 'ColorfulWoodUIUser' do

pod 'Masonry'
pod 'ColorfulWoodUIBase'
pod 'BmobSDK'
pod 'JKCategories'
pod 'ColorfulWoodUIBase'
pod 'ColorfulWoodTools'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'JSONModel'
pod 'SDWebImage'

end
