platform :ios, '8.0'

inhibit_all_warnings!

target 'TestUI' do

pod 'Masonry'
pod 'BmobSDK'
pod 'JKCategories'
pod 'ColorfulWoodCategories'
pod 'ColorfulWoodUIUser'
pod 'ColorfulWoodUIBase'
pod 'ColorfulWoodTools'
pod 'IQKeyboardManager', '~> 3.3.4'

end
