platform :ios, '8.0'

inhibit_all_warnings!

target 'TestUI' do

pod 'Masonry'
pod 'BmobSDK'
pod 'JKCategories'
pod 'ColorfulWoodUIBase'
pod 'ColorfulWoodTools'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'JSONModel'
pod 'SDWebImage'
end
